# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - main
    paths-ignore:
      - lerna.json

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          scope: radicalimaging
      - run: lerna version patch --yes
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: lerna publish --loglevel verbose --ignore-scripts --yes --canary --registry "https://npm.pkg.github.com/" --force-publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
